name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  webview_flutter: ^4.9.0
  package_info_plus: ^8.0.3
  url_launcher: ^6.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/Map(1).png
   - assets/Map(2).png
   - assets/Map(3).png
   - assets/Map(4).png
   - assets/Map(5).png
   - assets/Enemy1.png
   - assets/Enemy2.png
   - assets/Enemy3.png
   - assets/light.png
