name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.9.0
  package_info_plus: ^8.0.3
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.2
  get: ^4.6.6
  hive_flutter: ^1.1.0
  introduction_screen: ^3.1.14

  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  firebase_database: ^11.0.1
  shared_preferences: ^2.3.3
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/Map(1).png
   - assets/Map(2).png
   - assets/Map(3).png
   - assets/Map(4).png
   - assets/Map(5).png
   - assets/Enemy1.png
   - assets/Enemy2.png
   - assets/Enemy3.png
   - assets/Camera_icon.png
   - assets/splash_image.jpg
   - assets/blue-light.png
   - assets/red-light.png
   - assets/green-light.png
   - assets/CreateImage.jpg
   - assets/Splash_Image1.jpg
   - assets/Manual(1).png
   - assets/Manual(2).png
   - assets/Manual(3).png
   - assets/logo1.png
   - assets/rank_back.jpg

   
  #スプラッシュ画面の設定
flutter_native_splash:
  color: "#42a5f5"
  image: assets/Splash_Image1.jpg
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true
